name: Deploy React App

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        working-directory: ./novo_curriculo
        run: npm install

      - name: Build
        working-directory: ./novo_curriculo
        run: npm run build

      - name: Deploy
        working-directory: ./novo_curriculo
        run: npx gh-pages -d build
