name: Deploy React App

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        working-directory: ./novo_curriculo
        run: npm install

      - name: Configurar Git
        run: |
          git config --global user.name "AX414"
          git config --global user.email "joaovictorlisboaporcel@hotmail.com"

      - name: Deploy
        working-directory: ./novo_curriculo
        run: npm run deploy
